name: Post Code Coverage on Pull Request

on:
  workflow_run:
    workflows: [Build and deploy]
    types:
      - completed

defaults:
  run:
    shell: pwsh

jobs:
  post-code-coverage:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download artifacts
        run: gh run download ${{ github.event.workflow_run.id }} -n CodeCoverage --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: 'Get PR Number'
        id: get-pr-number
        run: |
          $pr_number = (cat PullRequestNumber)
          "pr_number=$pr_number" >> $env:GITHUB_OUTPUT

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          number: ${{ steps.get-pr-number.outputs.pr_number }}
          path: SummaryGithub.md